services:
  quay:
    image: "registry:2.8.3"
    container_name: "quay"
    restart: always
    volumes:
      - "./quay/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5000:5000"

  ghcr:
    image: "registry:2.8.3"
    container_name: "ghcr"
    restart: always
    volumes:
      - "./ghcr/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5001:5000"

  gcr:
    image: "registry:2.8.3"
    container_name: "gcr"
    restart: always
    volumes:
      - "./gcr/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5002:5000"

  docker:
    image: "registry:2.8.3"
    container_name: "docker"
    restart: always
    volumes:
      - "./docker/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5003:5000"

  k8s:
    image: "registry:2.8.3"
    container_name: "k8s"
    restart: always
    volumes:
      - "./k8s/config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5004:5000"

  ghproxy:
    image: "ghcr.io/sky22333/hub-proxy"
    container_name: "ghproxy"
    restart: always
    ports:
      - "5005:5000"